const BOOL_PATTERN = /^(?:IS_|HAS_|ENABLE_|DISABLE_|USE_|MAINTENANCE_)/;
const NUM_PATTERN =
  /(?:_PORT|_TIMEOUT|_COUNT|_SIZE|_LIMIT|_ID|_AGE|_LEVEL|_NUMBER|_TTL|_MAX|_WINDOW|_EXPIRATION|MAX_.*_SIZE|.*_SIZE_MB)$/;
const UNSAFE_CHARS = /[<>:"|?*\x00-\x1f]/g;
const CONTROL_CHARS = /[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g;
const VALID_KEY = /^[A-Z_][A-Z0-9_]*$/i;
const PATH_TRAVERSAL = /\.\./;

export {
  BOOL_PATTERN,
  NUM_PATTERN,
  UNSAFE_CHARS,
  CONTROL_CHARS,
  VALID_KEY,
  PATH_TRAVERSAL,
};
